# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  host: localhost
  port: 3306
  database: redbooth_housework
  username: root
  password: ""
      
test:
  adapter: mysql
  host: localhost
  port: 3306
  database: redbooth_housework_test
  username: root
  password: ""
  
production:
  adapter: mysql
  host: localhost
  port: 3306
  database: redbooth_housework_production
  username: root
  password: ""
  

      
      