# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  host: localhost
  port: 3306
  database: redbooth_housework
  username: root
  password: ""
  
production:
  adapter: postgres
  host: ec2-54-243-245-159.compute-1.amazonaws.com
  port: 5432
  database: deb2qpjub5640k
  username: zlatpxtnmedqmc
  password: HfKnCK2-ugE8oFuya0uRhCMVhG
  

      
      